trigger:
  branches:
    include:
      - main
      - ll-/*
      - fix-/*

pr:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Use the self-hosted agent instead of Microsoft-hosted

variables:
  NODE_VERSION: '22.13.1'

steps:
  # 🔹 Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js'

  # 🔹 Cache Node Modules (Speed Up Builds)
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | frontend/package-lock.json | backend/package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(NPM_CACHE_FOLDER)
    displayName: 'Cache npm dependencies'

  # 🔹 Lint & Test Frontend (Angular)
  - script: |
      cd frontend
      npm install
      npm run lint
      npm run test -- --watch=false --browsers=ChromeHeadless
    displayName: 'Lint & Test Angular Frontend'

  # 🔹 Build Angular App
  - script: |
      cd frontend
      npm run build -- --configuration=production
    displayName: 'Build Angular App'
