trigger:
  branches:
    include:
      - main
      - ll-/*
      - fix-/*

pr:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Use the self-hosted agent instead of Microsoft-hosted

variables:
  NODE_VERSION: '22.13.1'

steps:
  - checkout: self

  # 🔹 Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js'

  # 🔹 Build Angular App
  - script: |
      cd frontend
      npm run build -- --configuration=production
    displayName: 'Build Angular App'
