trigger:
  branches:
    include:
      - main
      - feature/*
      - bugfix/*

pool:
  name: 'Default'

steps:
  - checkout: self  # ✅ Ensure repo is cloned

  - script: |
      cd frontend
      npm install
    workingDirectory: $(Build.SourcesDirectory)/frontend
    displayName: 'Install Angular Dependencies'

  - script: |
      cd frontend
      npm run build -- --configuration=production
    workingDirectory: $(Build.SourcesDirectory)/frontend
    displayName: 'Build Angular App'
